<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V8VSACL" failures="2" tests="4" name="Test" time="0.25" errors="0" timestamp="2022-08-24T10:17:00 IST">
  <testcase classname="failedTestCasesExecution.FailedTestExecution" name="test1" time="0.02"/>
  <testcase classname="failedTestCasesExecution.FailedTestExecution" name="test2" time="0.004">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at failedTestCasesExecution.FailedTestExecution.test2(FailedTestExecution.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="failedTestCasesExecution.FailedTestExecution" name="test3" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failedTestCasesExecution.FailedTestExecution.test3(FailedTestExecution.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="failedTestCasesExecution.FailedTestExecution" name="test4" time="0.003"/>
</testsuite> <!-- Test -->
